name: Deploy to vps

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            cmv-web/dist
            cmv-backend/dist
            docker-compose.yml
            cmv-web/Dockerfile
            cmv-backend/Dockerfile
          target: /usr/var/html
          strip_components: 0

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /usr/var/html
            docker-compose down || true
            docker-compose pull
            docker-compose up --build -d
            docker image prune -f
            docker ps