name: Node.js CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:22-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      # Installer les dépendances et exécuter les commandes pour le backend
      - name: Install and Test Backend
        working-directory: ./cmv-backend
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_db
        run: |
          npm install
          npm run build --if-present
          npx prisma migrate deploy
          npx prisma db seed
          npm test

      # Installer les dépendances et exécuter les commandes pour le frontend
      - name: Install and Test Frontend
        working-directory: ./cmv-web
        run: |
          npm install
          npm run build --if-present
          npm test
