#!/usr/bin/env sh

npx lint-staged

# Run backend tests
cd cmv-backend && NODE_OPTIONS='--experimental-vm-modules' npx jest --forceExit --passWithNoTests
cd ..

# Run frontend tests
cd cmv-web && npx vitest run --passWithNoTests
cd ..
