name: Node.js CI

on:
  push:
    branches: [ test ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:22-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install OpenSSL
        run: apt-get update -y && apt-get install -y openssl
      # Installer les dépendances et exécuter les commandes pour le backend
      - name: Install and Test Backend
        working-directory: cmv-backend
        env:
          DATABASE_URL: postgresql://test:test@postgres:5432/test_db
        run: |
          npm install
          npx prisma migrate deploy
          npx prisma db seed
          npm test
