name: Node.js CI

on:
  pull_request:
    branches: [ dev ]

  push:
    branches: [ fix/bug ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:22-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Test Backend
        working-directory: ./cmv-backend
        env:
          DATABASE_URL: postgresql://test:test@postgres:5432/test_db
          PORT_GATEWAY: 3000
          PORT_SERVICE_IT: 3001
          PORT_SERVICE_FLEET: 3002
          CORS_ORIGIN: 'http://localhost:5173'
          JWT_SECRET_KEY: "JgGoWl+JCmMMQTfZ6tvu8hqI7HQLkZ/Z9CeVRzvs9Ylv"

        run: |
          apt-get update -y
          apt-get install -y openssl
          npm install
          npx prisma migrate deploy
          npx prisma db seed
          npm test