name: Deploy to vps

on:
  push:
    branches: [ fix/bug ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies and build
        run: |
          cd cmv-backend
          npm install
          npm run build
          cd ../cmv-web
          npm install
          npm run build

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "cmv-web/dist/*, cmv-backend/prisma/*, cmv-backend/views/*, cmv-backend/dist/*, compose.yaml, cmv-backend/Dockerfile, cmv-backend/package.json, cmv-backend/package-lock.json, conf/*"
          target: /var/html/clinique-monvert
          strip_components: 0
          debug: true

      - name: Create .env file backend
        run: echo "${{ secrets.ENV_FILE_BACK }}" > .env

      - name: Copy .env to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ".env"
          target: /var/html/clinique-monvert/cmv-backend

      - name: Start docker-compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /usr/var/html/clinique-monvert/
            docker compose down || true
            docker compose pull
            docker compose up --build -d
            docker image prune -f
            docker ps