name: Deploy to vps

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            cmv-web/dist
            cmv-backend/dist
            docker-compose.yml
            cmv-web/Dockerfile
            cmv-backend/Dockerfile
            cmv-backend/package.json
            cmv-backend/package-lock.json
          target: /usr/var/html/clinique-monvert
          strip_components: 0

      - name: Create .env file backend
        run: echo "${{ secrets.ENV_FILE_BACK }}" > .env

      - name: Copy .env to VPS
        uses: appleboy/scp-action@v0.2.4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ".env"
          target: "/usr/var/html/clinique-monvert/cmv-backend" 

      # - name: Start docker-compose
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ secrets.VPS_IP }}
      #     username: ${{ secrets.VPS_USER }}
      #     port: ${{ secrets.VPS_PORT }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /usr/var/html
      #       docker-compose down || true
      #       docker-compose pull
      #       docker-compose up --build -d
      #       docker image prune -f
      #       docker ps