name: Deploy app

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install --only=prod
      - run: npm run build
      - name: Deploy to vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/home/danielwetan/apps/node1
            git pull origin main
            git status
            pm2 restart node1
            cd ../../
            cd folder vue js
            pm2 restart vue js